version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - build_folder:/frontend/build
      - ./frontend/node_modules/:/frontend/node_modules
    stdin_open: true 
    tty: true
    env_file:
      - ./frontend/.env.local

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: >
      bash -c "python3 manage.py makemigrations gdiary &&
                python3 manage.py makemigrations text && 
                python3 manage.py migrate gdiary &&
                python3 manage.py migrate text &&
                gunicorn config.wsgi --bind 0.0.0.0:8000"
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./backend/.env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    ports:
      - 5672:5672 # Default Port
      - 15672:15672 # For UI
    volumes:
      - ./backend:/backend
    depends_on:
      - backend
    expose:
      - "15672"

  celery:
    container_name: celery
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - backend
      - rabbitmq
    volumes:
      - ./backend:/backend
    command: "celery -A config.celery worker --loglevel=info --pool=solo"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:8080
    restart: always
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  static_volume: null
  media_volume: null
  build_folder: null
